//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fetching_Price_BetweenTwo_Range.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int pro_id { get; set; }
        public string Pro_Company { get; set; }
        public string Pro_Name { get; set; }
        public string Pro_Descripton { get; set; }
        public Nullable<int> Pro_Price { get; set; }
    }
}
